import 'package:in_app/app/controllers/product/production_controller.dart';

/// Generated by Karee 

extension ProductionControllerExtension on ProductionController {
	static late final ProductionController? service;
	static bool loaded = false;
	void init(){
		ProductionControllerExtension.service = this;
		ProductionControllerExtension.loaded = true;
	}
	ProductionController get self {
		init();
		return this;
	}
}

ProductionController get $extendedProductionController {
	if(!ProductionControllerExtension.loaded){
		ProductionController().self;
	}	return ProductionControllerExtension.service!;
}