import 'package:in_app/app/controllers/auth/authentication_controller.dart';

/// Generated by Karee 

extension AuthenticationControllerExtension on AuthenticationController {
	static late final AuthenticationController? service;
	static bool loaded = false;
	void init(){
		AuthenticationControllerExtension.service = this;
		AuthenticationControllerExtension.loaded = true;
	}
	AuthenticationController get self {
		init();
		return this;
	}
}

AuthenticationController get $extendedAuthenticationController {
	if(!AuthenticationControllerExtension.loaded){
		AuthenticationController().self;
	}	return AuthenticationControllerExtension.service!;
}